language: node_js
node_js:
  - '0.12'
sudo: false
env:
  matrix:
    - GROUP=
  global:
    - GHREPO=github.com/phosphorjs/phosphor-splitpanel
    - secure: m37xiGxyXk+KxhVJimAxarn+b/Yqzv5rw3d9FT2JqyHnvgmo0VQmfUOSy3gxb9AtYlhE9TOkh1pcWD9zBXsVBnvJS1aCSouASB/6hhyApGHnT2Wym2kmaTUkUp9+PqO0nAhPXzEueidLE7m48HZ6ZclduzMfzGQ72WE86UEgev8I8gJaXfHvQAum03JuQZ/66wMDZf0iA41YGTXHSS4rKbIivvgeHPT1VwRlbsRGNH95E9rkHQW6/Lk8fhL92Z+M4ICGbaW1xle25+TSITHYQepWd2oVzIL+X/r4xZ2ztP8xlgs3nr/Rbw5Za5/EPdLbJGMu2tYpFk97O+EOok0o0Bx0jn8GA9zRsVLBivRql+4dUoOMprN3x/nEJA1a23nALPxjM1sm9JSkgVnDKa2WWdM5fd6aAfu/CyGA1W0HbG7WbSUHkGjRm+9JaAhjCXRVTD8CoD7LjrlL27pqXcIpASAoJJtq/4CbIOyEB0DOiwKOegviYU2CAaErK30pbJpRTuPhGr9nvMNoacoc2fKVfIWU3URwK7OgwEVgqD0lvRff+XR7behwo7tuvyO1gYUEw9h7YuQNpdiK/0THxMfxqJpXEjwNZuPbMjtwLgIZ7kgu6ER/EJkyopF18PQl4CPyQaSXKpw5kHKKRGUA22uv7vdWgdABjuAgNkuMOZdvccQ=
install:
  - bash ./scripts/travis_install.sh
script:
  - bash ./scripts/travis_script.sh
after_success:
  - bash ./scripts/travis_after_success.sh
